[package]
name = "websocket_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket="0.27.1"
jwt="0.16.0"
hmac="0.12.1"
sha2="0.10.8"
serde="1.0.203"
